### PR TITLE
[Reviewer: Rob] Add sas event

### PR DESCRIPTION
**Pull request by eleanor-merry**
Rob, can you review this new SAS event for when deregistering with an application server fails

### CODE REVIEW

**Comment by rkd-msw** [comment]
Looks good. Do we have the AS URL in hand to pass into the SAS event as well, or is that buried within the IFC-handling code?

(Also, when do we trigger this? Does it come up when we get e.g. a 503 error form an AS, or is it just for the failed-to-build-a-message case from https://github.com/Metaswitch/sprout/pull/967)?

**Comment by eleanor-merry** [comment]
We don't have the AS URL, and it's only used for the failed-to-build-a-message case

**Comment by rkd-msw** [comment]
I think we already have https://github.com/Metaswitch/clearwater-sas-resources/blob/iss966/clearwater_sas_resource_bundle.yaml#L589 (`const int REGISTER_AS_FAILED = SPROUT_BASE + 0x000083`) for that case as a level 80 log - could you just raise that and then (maybe) have an engineering-level log specifically saying that we couldn't build a PJSIP response?

**Comment by eleanor-merry** [comment]
As discussed, I'm going to update the text to make it clear this is just for a deregistration, rather than use the existing SAS event and passing in an error string

**Comment by rkd-msw** [comment]
Registration-Termination-Request-triggered deregistration in particular, I thought?

**Pull request merged**
