### PR TITLE
[Reviewer AJH]: SAS trace HSS returncodes

### PR DESCRIPTION
**Pull request by steelyvoid**
See associated Homestead PR https://github.com/Metaswitch/homestead/pull/354

### CODE REVIEW

**Comment by AlexHockey** [comment]
Passing back to you to implement the changes agreed in https://github.com/Metaswitch/homestead/pull/354

**Comment by AlexHockey** [comment]
Looks good. Two comments:

1. I think that sometimes the (experimental) result code will be zero, which isn't a valid entry in either enum. What does this look like in the UI? If it looks bad, I'm happy with you adding a 0 value to the enum. 
2. Please can you update the resource bundle ID (and make the cor-req cpp-common and submodule updates).

Passing back to you to co-ordinate the merge.

**Comment by steelyvoid** [comment]
Thanks Alex
In answer to the first question, if either code is "0" it just gets displayed as "0" (not, e.g., "Undefined value!!! Whoop Whoop!), so I think we're fine here

**Comment by AlexHockey** [comment]
Great, thanks for checking.

**Pull request merged**
